pytest_httpserver/httpserver.py

Start HTTPServer on ephemeral port by default

---

pytest_httpserver/httpserver.py
tests/test_mixed.py
tests/test_oneshot.py
tests/test_ordered.py

This change is not backward compatible!
1. Define enum `HandlerType`.
2. Make `expect_request` universal so that it could register permanent,
oneshot, and ordered handlers by adding enum `HandlerType` argument with
default value `HandlerType.PERMANENT`.
3. Remove ordered argument from expect_oneshot_request.
4. Add convenience method expect_ordered_request.
Fixes #9.

Unify expect_request functions

---

tests/test_wait.py

In pytest raises() returns an info object whose `value` attribute contains
the actual exception caught.
Converting to string used to work but currently it returns a string which
does not contain the exception text, so it is better to check for the actual
exception object instead.

test_wait.py: fix tests testing exception

---

pytest_httpserver/httpserver.py
releasenotes/notes/fix-16-query-string-c989bee73733a325.yaml
tests/test_querystring.py

In werzeug the requets.query_string is a bytes object so expecting a string
in the RequestMatcher breaks the query_string matching functionality. Users
can provide a bytes object but in this case they will break the official
API.
In order to not break the API, an implicit conversion is added which
converts the string object to bytes. Accepting bytes is also added in case
the user does not want this implicit behavior.
Fixes #16

httpserver: fix query_string type

---

pytest_httpserver/httpserver.py
tests/test_querymatcher.py
tests/test_querystring.py

If query_string is specified as a Mapping (dict), the query string of the
request will be parsed and will be matched with the dictionary specified.
When a key has multiple values in the request (eg. "foo=bar&foo=baz"), the
first item will be used.
If it is desired to match all the values from the same key, use
werkzeug.datastructures.MultiDict instance, as it can hold multiple values
for the same key.

httpserver: add query matcher feature

---

doc/guide.rst
pytest_httpserver/__init__.py
pytest_httpserver/httpserver.py
releasenotes/notes/uri-matching-dba6660cb0689402.yaml
tests/test_urimatch.py

Extend URI matching functionality which now accepts:
* a URIPattern object, whose match() method will be called
* a compiled regexp returned by re.compile(). In this case the
URI will be matched against the regexp.
In both cases the URI will be an absolute path starting with a slash.
Fixes #34 and #36.

httpserver: add URI matching

---

pytest_httpserver/httpserver.py
releasenotes/notes/http-methods-are-case-insensitive-c2a1d49f9809f263.yaml
tests/test_permanent.py

When creating a matcher, it should not matter whether the method is
specified as 'get' or 'GET'. At the end it will be converted to uppercase.
Fixes #40.

httpserver.py: make http method case-insensitive

---

pytest_httpserver/httpserver.py
releasenotes/notes/no-handler-status-code-380fa02ebe9b2721.yaml
tests/test_permanent.py

The http response code sent when no handler is found for the request can be
changed. It is set to 500 by default.
Fixes #44.

httpserver: http response code for no handler can be specified

---

Makefile
doc/howto.rst
example_pytest.py
pytest_httpserver/pytest_plugin.py
setup.cfg
tests/conftest.py
tests/test_ssl.py
tox.ini

* Replaces the ```PluginHTTPServer``` and ```Plugin``` classes by a ```session```-scoped fixture that automatically manages the lifetime of the server instance thus removing the need for a ```pytest_sessionfinish``` hook.
* Makes sure that the server is cleaned directly after each test function and not at the start of the next test function as before. This way other test functions in the same module will not be affected by previous tests (even if they don't require the ```httpserver``` fixture)
* Adds a way to configure the SSL-context if the test function requires an HTTPS connection. This is achieved by a new fixture ```httpserver_ssl_context``` which works similarly to how the IP-address and port are configured using ```httpserver_listen_address```
* Promotes the scope of …

plugin instance as fixture + SSL support in pytest

---

doc/howto.rst

I had to implement this [for `vdirsyncer`'s test suite](https://github.com/pimutils/vdirsyncer/pull/903), and this might save the next person needing it some headaches.

Add a howto entry on how to create an HTTPS server

---

.gitignore
pytest_httpserver/httpserver.py
tests/test_handler_errors.py

This PR fixes #63
I went for option 1 as proposed in #63 
>     * I'm thinking about the effect of adding a catch all exception handler so every exception (including AssertionError of course) would be re-raised in the check_assertions() call. But I'm unsure about how it would break the code of the users. What do you think?
The way it is implemented now should not break user code, as exceptions from handlers are collected and then re-raised.
I also added `__pycache__` to the `.gitignore`

httpserver: propagate event handler exceptions to httpserver

---

doc/background.rst

- Removing a double 'the'.
- Fixing a syntax error s/made/make

Fixing typos and syntax errors in the documentation

---

pytest_httpserver/httpserver.py
tests/test_headers.py

This can accept a mapping or a list of 2-element tuples. In this latter
case, multiple values can be specified for the same header.
A testcase is added for this.
Fixes #132

respond_with_data: fix headers type hinting

---

pyproject.toml

Fix the `include` directives to include the specified files in sdist
only.  Without explicit format, they cause the specified files to be
included both in sdist and in wheels, which in turn means they're going
to be installed into the top-level directory of site-packages!

fix pyproject.toml not to install various files into site-packages

---

.github/workflows/ci.yml
poetry.lock
pyproject.toml

3.6 support has ended on 23 Dec 2021, and CI cannot be run with the latest werkzeug and other packages because poetry installs the requirements which work on 3.6.
Nearly all of the dependencies have update minimum python to 3.7 so it is better to follow them.

update minimum python requirement to 3.7

---

README.md
pytest_httpserver/__init__.py
pytest_httpserver/blocking_httpserver.py
pytest_httpserver/httpserver.py
tests/test_blocking_httpserver.py
tests/test_release.py

Rename 'Http' to 'HTTP' to be consistent.
Rename 'blocking_http_server.py' for the same reason.
'Http' would be a better choice but we don't want to have API
incompatibility and as HTTP is all uppercase everywhere it is better to keep
aligned with that.

blocking_http_server: rename classes and module

---

pytest_httpserver/blocking_httpserver.py
pytest_httpserver/httpserver.py

Restore API compatibility for the parameters specified by position, and also
remove the `**kwargs` from the constructors and replace it with the real
parameters to make the documentation better (and to also help IDE
integration). Update documentation.

httpserver: replace **kwargs with named parameters

---

README.md
doc/api.rst
pytest_httpserver/__init__.py
pytest_httpserver/blocking_httpserver.py

Follow-up renamings, add blocking http server classes to the documentation
and fix cross-references.

doc: fix and update documentation

---

doc/howto.rst
tests/test_blocking_httpserver_howto.py

It is recommended to call check_assertions() at the end of the test run to
check if there were any requests made by the client which were not handled
at all.
In that case the server registers that there was an error and this needs to
be checked at the end.

howto: fix blocking httpserver howto

---

pyproject.toml
tests/test_release.py

pyproject.toml: remove classifiers
Python classifiers are generated by poetry, so there's no need to specify
them manually. Otherwise, poetry generates duplicate classifiers.
Test added to avoid having duplicate classifiers in the future.

pyproject.toml: remove classifiers

---

CHANGES.rst
doc/conf.py
pyproject.toml
releasenotes/notes/blocking-httpserver-3b58e2a8464b4d97.yaml

- release_notes: add release note about the blocking httpserver
- Version bump to 1.0.6
- CHANGES.rst: add release notes for 1.0.6

Release version 1.0.6

---

pytest_httpserver/httpserver.py
pytest_httpserver/pytest_plugin.py
tests/test_ip_protocols.py
tests/test_release.py

This follows the discussion on #182.
I added two fixtures that forces the use of IPV4 or IPV6. I am not really happy with the code duplication, so ideas are welcome.
`url_for` had to be edited to add brackets, because `http://::1:443` is not valid, but `http://[::1]:443` is. However IPV6 should be passed to werkzeug without brackets because [some libc implementations does not support them](https://github.com/python/cpython/issues/85341#issuecomment-1253754541). The implementation could maybe have been cleaner with [urlunsplit](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlsplit) but sadly it does not support port arguments.
Tell me if the implementation looks OK, and then I will write some documentation.
Fixes #182

Added IPV4 and IPV6 only fixtures

---

pytest_httpserver/httpserver.py

This needs to be made a bit more exact, added note about IPv6 and TLS.

httpserver: update docstrings of url_for method

---

.github/actions/setup/action.yml
.github/workflows/ci.yml
.vscode/settings.json
poetry.lock
pyproject.toml
pytest_httpserver/httpserver.py
releasenotes/notes/werkzeug-header-type-follow-up-74a80dd03e6ca6db.yaml
releasenotes/notes/werkzeug-parse_authorization_header-deprecation-fix-8264966b70fddc6d.yaml
releasenotes/notes/werkzeug-urls-url_decode-deprecation-fix-56fe3c183b53f83b.yaml
tests/test_headers.py
tests/test_parse_qs.py
tests/test_release.py

- poetry: update python to >=3.8 to install the latest werkzeug
- httpserver.py: remove the now deprecated werkzeug.urls.url_decode call
- httpserver.py: fix werkzeug deprecated parse_authorization_header call

werkzeug deprecation warnings fix

---

.github/actions/setup/action.yml
releasenotes/notes/python-37-deprecation-72029b78e91d6b26.yaml
tests/test_release.py

- cleanup: remove comments which are not needed
- test_release.py: remove unused parameter
- releasenotes: add release note about python 3.7 deprecation

python deprecation

---

tests/examples/test_example_blocking_httpserver.py

Remove this call as it is not needed here.

test_example_blocking_httpserver.py: remove httpserver.clear()

---

pytest_httpserver/httpserver.py
releasenotes/notes/requesthandler-repr-09f342f19f6250bc.yaml
tests/test_permanent.py

Add `__repr__` to support pytest's diff view.
Such case is when oneshot_handlers are compared with an empty list `[]`.
Fixes #273.

RequestHandler: add __repr__

---

pytest_httpserver/httpserver.py
tests/test_blocking_httpserver.py

When a Request is not handled and thus triggers the nohandler, it can be very useful to have a more verbose output to indicate which Request is unhandled.
This is particularly useful when you are in a test cycle and trying to determine which requests is mismatching.

HTTPServerBase: change Request to be more verbose respond_nohandler

---

Makefile
doc/api.rst
doc/conf.py
doc/howto.rst
doc/patch.py
pyproject.toml
pytest_httpserver/__init__.py
pytest_httpserver/httpserver.py
releasenotes/notes/log-querying-683219f3587d2139.yaml
shell.nix
tests/examples/test_howto_log_querying.py
tests/test_log_querying.py
tests/test_release.py

Add log querying methods for httpserver. This is to query if a request has been made for the server. It also allows to check if the request was made 0, 1 or more times.
The functionality is split to 3 methods for the sake of flexibility, so users who want to check for `>` or `<` relations with the numer of request matched can implement their own logic.

Add log querying methods

---

.readthedocs.yml

This time the official recommendation used:
https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry

.readthedocs.yml: fix rtd build

---

pytest_httpserver/httpserver.py
tests/test_release.py
tests/test_threaded.py

Closes: https://github.com/csernazs/pytest-httpserver/issues/323
No risk of leaving threads behind: werkzeug.ThreadedWSGIServer uses socketserver.ThreadingMixIn, which adds a `self._threads.join()` in its `server_close`. `self._threads.join()` is called before `self.server.serve_forever()` returns, so before `self.server_thread.join()` returns, so before `self.stop()` returns.
The wording "handle concurrent requests in separate threads" was taken from the ThreadedWSGIServer documentation.

Enable processing concurrent requests in separate threads

---

doc/api.rst
doc/howto.rst
pytest_httpserver/hooks.py
pytest_httpserver/httpserver.py
releasenotes/notes/hooks-306915ded3b2771f.yaml
tests/examples/test_howto_custom_hooks.py
tests/examples/test_howto_hooks.py
tests/test_hooks.py
tests/test_release.py

This will allow users to define one callable object (a hook) for each request handler, which will be called right before returning the response.
The hook has the possibility to return a new response object which will be used instead of the original one. The callback (hook) will receive the request and response objects.

Add hooks functionality

---

doc/howto.rst
pytest_httpserver/httpserver.py
tests/examples/test_howto_custom_hooks.py
tests/examples/test_howto_hooks.py
tests/test_hooks.py

This is to make it possible to implement with_pre_hook in the future.

hooks: rename with_hook to with_post_hook

---

releasenotes/notes/fix-test_verify_assert_msg-af37678f187bb8da.yaml
tests/test_log_querying.py

Accept-Encoding is constructed dynamically by the availability of the
compression libraries (eg.  zstd, zstandard) so it can result failed test at
the end.
Fixes #345

tests: fix test_verify_assert_msg by setting Accept-Encoding

---

pytest_httpserver/pytest_plugin.py

I believe it makes sense to clear the server state **before** performing a test rather than after, starting each test in a fresh state.
Consider the following case:
```python
@fixture
def my_fixture() -> DoesSomeHTTPRequests:
start_thread()
yield obj
stop_thread()
def test_function_1(my_fixture: DoesSomeHTTPRequests, httpserver: HTTPServer) -> None:
my_fixture.make_thread_communicate_with(httpserver.url_for('/'))
def test_function_2(httpserver: HTTPServer) -> None:
assert len(httpserver.log) == 0
```
In that case - `test_function_2` may receive leaked logs from `test_function_1` since `my_fixture` is destructed only **after** `httpserver` and therefore the fixture would be able to send requests to the server **after** the state is cleared.
One could argue that swapping the fixtures order …

httpserver: Clear state in function-scoped fixtures before the test

---

.github/workflows/ci.yml
poetry.lock
pyproject.toml
tests/test_release.py

Fallback to tomli, which is the same project,
rather than toml which wasn't updated for a while.

Where available, use tomllib from the standard library

---

pytest_httpserver/httpserver.py
tests/test_matcher.py
tests/test_release.py

I wasn't able to match a request I was making and it turned out that I was serializing a set, and therefore wouldn't know the order of the JSON list that gets serialized. Due to the way JSON is compared in this library, order does matter (even if you pass a structure with a set to `json=`).
So I think it makes sense to allow passing in some sort of open interface or simply accept RequestMatcher and consumers could override methods.
This would allow composing RequestMatcher with [deepdiff](https://github.com/seperman/deepdiff) to do order insensitive matching or *anything* else you'd want to do.

Configurable expect method

---

pytest_httpserver/httpserver.py
tests/test_release.py
tests/test_thread_type.py

In the [LocalStack](https://github.com/localstack/localstack/) test codebase we heavily use LocalStack to test integrations of our emulated AWS services. Thanks for the great project!
In the past we were facing issues with our integration tests timing out due to shutdowns being blocked. It turns out that some of the `pytest-httpserver` threads were not properly shut down. @bentsku fixed this by patching the `HTTPServer` class to spawn a deamon thread to make sure that it cannot block the shutdown of the interpreter with https://github.com/localstack/localstack/pull/10052.
This patch broke with the latest release, as the `start` method was modified (which is why we did not upgrade to the latest version 1.1.2, but introduced an upper limit with …

prevent shutdown issues by making server thread daemonic

---

.github/workflows/ci.yml

- **[pre-commit.ci] pre-commit autoupdate**
- **CI: upgrade poetry to 2.1.1 as dependabot uses it already**

upgrade poetry itself

---

doc/tutorial.rst

Add example from #68 to the documentation.

doc: improve tutorial
